services:
    nginx:
        image: ${DOCKER_IMAGE:-dubnahirudo:latest}
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx:/etc/nginx:ro
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./certbot/logs:/var/log/letsencrypt
        depends_on:
            - certbot
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'''
        restart: unless-stopped

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./certbot/logs:/var/log/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        restart: unless-stopped
