name: Test

on:
    push:
        tags-ignore:
            - 'v[0-9]+.[0-9]+.[0-9]+'

    pull_request:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # setup bun - start
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Bun Runtime
              uses: antongolub/action-setup-bun@v1
              with:
                cache: true

            - name: Install dependencies
              run: bun install --production --frozen-lockfile
            # setup bun - end

            - name: Check types
              run: bun run tsc
