name: Test

on:
    push:
        tags-ignore:
            - 'v[0-9]+.[0-9]+.[0-9]+'

    pull_request:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # setup bun - start
            - name: Checkout
              uses: actions/checkout@v3

            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Get bun store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$HOME/.bun/install/cache" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup bun cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-store-

            - name: Install dependencies
              run: bun install --production --frozen-lockfile --cache-dir $STORE_PATH
            # setup bun - end

            - name: Check types
              run: bun run tsc
